name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: nixos
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: nix build --quiet

      - name: Check formatting
        run: nix develop --quiet -c just format-check

      - name: Lint
        run: nix develop --quiet -c just hlint
